import docSitemap from 'docs/routes/docSitemap';
import paths, { rootPaths } from './paths';

const sitemap = [
  {
    id: 'homepage',
    subheader: 'Homepage',
    items: [
      {
        name: 'Dashboard',
        key: 'dashboard',
        path: rootPaths.root,
        pathName: 'dashboard',
        icon: 'material-symbols:space-dashboard-outline-rounded',
        active: true,
      },
      {
        name: 'Email',
        icon: 'material-symbols:mail-outline-rounded',
        path: paths.email,
      },
      {
        name: 'Kanban',
        icon: 'material-symbols:view-kanban-outline-rounded',
        path: paths.kanban,
      },
      {
        name: 'Chat',
        path: paths.chat,
        icon: 'material-symbols:chat-bubble-outline-rounded',
      },
      {
        name: 'Social',
        path: paths.social,
        icon: 'material-symbols:account-box-outline',
      },
      {
        name: 'File manager',
        path: paths.fileManager,
        icon: 'material-symbols:folder-outline-rounded',
      },
      {
        name: 'Calendar',
        path: paths.calendar,
        icon: 'material-symbols:calendar-month-rounded',
      },
    ],
  },
  {
    id: 'pages',
    subheader: 'Pages',
    key: 'pages',
    icon: 'material-symbols:view-quilt-outline',
    items: [
      {
        name: 'Starter',
        key: 'starter',
        path: paths.starter,
        pathName: 'starter',
        icon: 'material-symbols:play-circle-outline-rounded',
        active: true,
      },
      {
        name: 'Notifications',
        key: 'notifications',
        path: paths.notifications,
        pathName: 'notifications',
        icon: 'material-symbols:notifications-outline-rounded',
        active: true,
      },
      {
        name: 'Events',
        key: 'events',
        pathName: 'events',
        icon: 'material-symbols:calendar-clock-outline-rounded',
        active: true,
        items: [
          {
            name: 'Create event',
            key: 'create_event',
            path: paths.createEvent,
            pathName: 'create-event',
            active: true,
          },
          {
            name: 'Event detail',
            key: 'event_detail',
            path: paths.events,
            pathName: 'event-detail',
            active: true,
          },
        ],
      },
      {
        name: 'Authentication',
        key: 'authentication',
        pathName: 'authentication',
        icon: 'material-symbols:security-rounded',
        active: true,
        items: [
          {
            name: 'Login',
            key: 'login',
            path: paths.defaultJwtLogin,
            pathName: 'login',
            active: true,
          },
          {
            name: 'Sign up',
            key: 'sign_up',
            path: paths.defaultJwtSignup,
            pathName: 'sign-up',
            active: true,
          },
          {
            name: 'Forgot password',
            key: 'forgot_password',
            path: paths.defaultJwtForgotPassword,
            pathName: 'forgot-password',
            active: true,
          },
          {
            name: '2FA',
            key: '2FA',
            path: paths.defaultJwt2FA,
            pathName: '2FA',
            active: true,
          },
          {
            name: 'Set password',
            key: 'set_password',
            path: paths.defaultJwtSetPassword,
            pathName: 'default-set-password',
            active: true,
          },
        ],
      },
      {
        name: 'Error 404',
        key: 'error_404',
        pathName: 'error',
        active: true,
        icon: 'material-symbols:warning-outline-rounded',
        path: paths[404],
      },
    ],
  },
  {
    id: 'misc',
    subheader: 'Misc',
    key: 'misc',
    icon: 'material-symbols:dashboard-customize-outline-rounded',
    items: [
      {
        name: 'Landing',
        key: 'landing',
        path: paths.comingSoon,
        pathName: 'landing',
        icon: 'material-symbols:flight-land-rounded',
      },
      {
        name: 'Account',
        key: 'account',
        path: paths.account,
        pathName: 'account',
        active: true,
        icon: 'material-symbols:admin-panel-settings-outline-rounded',
        new: true,
      },
      {
        name: 'Pricing',
        key: 'pricing',
        pathName: 'pricing',
        active: true,
        icon: 'material-symbols:sell-outline',
        hasNew: true,
        items: [
          {
            name: 'Pricing column',
            key: 'pricing_column',
            path: paths.pricingColumn,
            pathName: 'pricing-column',
            active: true,
          },
          {
            name: 'Pricing table',
            key: 'pricing_table',
            path: paths.pricingTable,
            pathName: 'pricing-table',
            active: true,
            new: true,
          },
        ],
      },
      {
        name: 'FAQ',
        key: 'faq',
        path: paths.faq,
        pathName: 'faq',
        selectionPrefix: 'faq',
        icon: 'material-symbols:question-mark-rounded',
        active: true,
      },
      {
        name: 'Multi level',
        key: 'multi_level',
        pathName: 'multi-level',
        icon: 'material-symbols:layers-outline-rounded',
        active: true,
        items: [
          {
            name: 'Level two (1)',
            key: 'level_two_1',
            path: '#!',
            pathName: 'multi-level-2',
            active: true,
          },
          {
            name: 'Level two (2)',
            key: 'level_two_2',
            pathName: 'multi-level-3',
            active: true,
            items: [
              {
                name: 'Level three (1)',
                key: 'level_three_1',
                path: '#!',
                pathName: 'multi-level-item-3',
                active: true,
              },
              {
                name: 'Level three (2)',
                key: 'level_three_2',
                path: '#!',
                pathName: 'multi-level-item-4',
                active: true,
              },
            ],
          },
          {
            name: 'Level two (3)',
            key: 'level_two_3',
            pathName: 'multi-level-4',
            active: true,
            items: [
              {
                name: 'Level three (3)',
                key: 'level_three_3',
                path: '#!',
                pathName: 'multi-level-item-6',
                active: true,
              },
              {
                name: 'Level three (4)',
                key: 'level_three_4',
                pathName: 'multi-level-item-7',
                active: true,
                items: [
                  {
                    name: 'Level four (1)',
                    key: 'level_four_1',
                    path: '#!',
                    pathName: 'multi-level-item-8',
                    active: true,
                  },
                  {
                    name: 'Level four (2)',
                    key: 'level_four_2',
                    pathName: 'multi-level-item-9',
                    active: true,
                    items: [
                      {
                        name: 'Level five (1)',
                        key: 'level_five_1',
                        path: '#!',
                        pathName: 'multi-level-item-10',
                        active: true,
                      },
                      {
                        name: 'Level five (2)',
                        key: 'level_five_2',
                        path: '#!',
                        pathName: 'multi-level-item-11',
                        active: true,
                      },
                    ],
                  },
                ],
              },
            ],
          },
        ],
      },
    ],
  },
  ...docSitemap,
];

export default sitemap;
