services:
  # Service de l'application Backend Django
  backend:
    build: ./backend  # Indique à Compose de construire l'image à partir du Dockerfile dans le dossier ./backend
    ports:
      - "8000:8000"  # Lie le port 8000 du conteneur au port 8000 de votre machine locale
    volumes:
      - ./backend:/app  # Monte le dossier local ./backend dans le /app du conteneur pour le rechargement automatique du code
    environment:
      - DB_NAME=nexusflow_db
      - SECRET_KEY='django-insecure-=yoursecretkeyhere!@#$qwer'
      - DB_USER=nexusflow_user
      - DB_PASSWORD=nexusflow_pass
      - DB_HOST=db
    command: /app/entrypoint.sh # Utilise notre script de démarrage pour appliquer les migrations
    depends_on:

      - db  # Indique que le service backend dépend du service db et doit attendre qu'il soit prêt    
    healthcheck:
      test: ["CMD-SHELL", "curl -f http://localhost:8000/ || exit 1"]
      interval: 10s
      timeout: 5s
      retries: 3
  
  # NOUVEAU: Service de l'application Frontend React
  frontend:
    build: ./frontend # Construit à partir du Dockerfile dans ./frontend
    ports:
      - "5173:5173" # Expose le port de Vite sur votre machine
    volumes:
      - ./frontend:/app # Monte le code source pour le rechargement à chaud
      - /app/node_modules # Astuce pour éviter que le node_modules local n'écrase celui du conteneur
    command: npm run dev -- --host --port 5173 # Force Vite à utiliser le port 5173
    depends_on:
      - backend # S'assure que le backend est lancé avant le frontend

  # Service de la base de données PostgreSQL
  db:
    image: postgres:15-alpine # Utilise une image officielle et légère de PostgreSQL
    container_name: nexus_db
    volumes:
      - postgres_data:/var/lib/postgresql/data/ # Crée un volume pour rendre les données persistantes
    env_file:
      - ./.env.dev
    environment:
      - POSTGRES_DB=nexusflow_db
      - POSTGRES_USER=nexusflow_user
      - POSTGRES_PASSWORD=nexusflow_pass
    ports:
      - "5432:5432" # Utile si vous souhaitez vous connecter à la BDD avec un outil externe

volumes:
  postgres_data:
    driver: local # Déclare le volume pour la persistance des données